# Generated by Django 3.2.5 on 2021-07-22 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('history', models.TextField(max_length=100)),
                ('pic', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.district')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=10)),
                ('vaccine', models.CharField(choices=[('Covaccine', 'Covaccine'), ('Covishield', 'Covishield'), ('Sputnic ', 'Sputnic')], max_length=10)),
                ('time', models.CharField(choices=[('9am', '9am'), ('2pm', '2pm'), ('4pm', '4pm')], max_length=10)),
                ('aadhar', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.center')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
