# Generated by Django 3.2.5 on 2021-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='authority',
            name='history',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='center',
            name='center',
            field=models.CharField(max_length=30),
        ),
    ]
